name: Redeploy Render Website

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger redeployment on Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          echo "Triggering redeployment..."
          curl -X POST "$RENDER_DEPLOY_HOOK"

      - name: Confirm redeployment
        run: echo "Redeployment triggered successfully at $(date)"
