name: Redeploy on Render

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 30 minutes

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeployment on Render
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Triggering redeployment via Render Deploy Hook..."
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"
